'use strict';

exports.BattleItems = {
	"imasiumz": {
		id: "imasiumz",
		name: "imasium Z",
		onTakeItem: false,
		zMove: "B O I",
		zMoveFrom: "Accele Squawk",
		zMoveUser: ["Skarmory"],
		gen: 7,
		desc: "If held by imas with Accele Squawk, it can use B O I.",
	}, 
	"tiksiumz": {
		id: "tiksiumz",
		name: "Tiksium Z",
		onTakeItem: false,
		zMove: "Devolution Wave",
		zMoveFrom: "Rock Slide",
		zMoveUser: ["Cradily"],
		gen: 7,
		desc: "If held by Tiksi with Rock Slide, it can use Devolution Wave.",
	},
	"tiksiumz": {
		id: "tiksiumz",
		name: "Tiksium Z",
		onTakeItem: false,
		zMove: "Devolution Wave",
		zMoveFrom: "Rock Slide",
		zMoveUser: ["Cradily"],
		gen: 7,
		desc: "If held by Tiksi with Rock Slide, it can use Devolution Wave.",
	},
	"roseradiumz": {
		id: "roseradiumz",
		name: "Roseradium Z",
		onTakeItem: false,
		zMove: "Relentless Rose Raid",
		zMoveFrom: "Sludge Wave",
		zMoveUser: ["Roserade"],
		gen: 7,
		desc: "If held by a Roserade with Sludge Wave, it can use Relentless Rose Raid.",
	},
	"singularity": {
		id: "singularity",
		name: "Singularity",
		onTakeItem: false,
		zMove: "Gamma Ray Burst",
		zMoveFrom: "Psystrike",
		zMoveUser: ["Sigilyph"],
		gen: 7,
		desc: "If held by Sigilyph with Psystrike, it can use Gamma Ray Burst.",
	},
};
